### ISSUE TITLE
Copying all styleguide names gets tedious

### ISSUE THREAD

**Issue by TheSonOfThomp** [zeplin/connected-components-beta-issues#7]
When you have one component linked to several styleguide instances, it gets really tedious to type each name, or copy one-by-one. It'd be nice to have a way to copy all the names of selected items in Zeplin, that can be easily pasted into the config file

**Comment by yuqu** [comment]
Hi Adam,

Our crews will brainstorm on your suggestion to be implemented into Zeplin. 

In the meantime, you may use our [VS Code extension](https://marketplace.visualstudio.com/items?itemName=zeplin.zeplin) to create the configuration file easily. 

Thanks for the suggestion, I'm closing this issue since we are out of beta and there is no public repository that this issue can live on. Please let me know if you have any other questions.
